apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookkeeper.fullname" . }}
  labels:
    {{- include "bookkeeper.labels" . | nindent 4 }}}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.tls.enabled }}
  - port: 443
  {{- else }}
  - port: 80
  {{- end }}
    targetPort: 8080
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort}}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: TCP
  selector:
    {{- include "bookkeeper.selectorLabels" . | nindent 8 }}
